import Foundation

/// Per-adapter command definitions for the machine-readable registry.
extension CommandRegistry {

    static let agent = group(name: "agent", description: "Global discovery commands for people, scripts, and agents.", subcommands: [
        leaf(name: "help", description: "Print global or adapter help. This is human-readable; use manifest for the machine-readable command contract."),
        leaf(name: "manifest", description: "Return the complete machine-readable command registry, safety metadata, exit codes, and JSON schemas under data.schemas."),
        leaf(name: "version", description: "Print the CLI release version; -v is an equivalent shorthand."),
    ])

    static let resources = leaf(
        name: "resources",
        description: "Discover every macOS data resource the CLI can access (Contacts, Mail, Calendar, Reminders, Photos, Notes, Shortcuts, Safari, Messages, and Call History), with selection state, authorization status, and read/write capabilities. Read-only; never prompts for permission.",
        outputSchema: "DataResourcesResult"
    )

    static let contacts = group(name: "contacts", description: "Query and manage contacts.", subcommands: [
        leaf(name: "permission", description: "Report the current Contacts authorization status without prompting. Read-only; grant or revoke access in System Settings → Privacy & Security → Contacts.", exitCodes: contactsExit),
        leaf(name: "containers", description: "List the available Contacts containers and mark which one is the selected iCloud container. Read-only.", exitCodes: contactsExit),
        leaf(name: "container", description: "Show the currently selected Contacts container (identifier, type, and iCloud flag). Read-only.", exitCodes: contactsExit,
        outputSchema: "ContactContainer"),
        leaf(name: "count", description: "Return the total number of contacts in the selected (iCloud) container. Read-only.", exitCodes: contactsExit),
        leaf(name: "list", description: "List contacts from the selected container with cursor pagination. Read-only; page size defaults to 50.",
             params: [int("limit", "Page size", default: "50"), string("cursor", "Opaque cursor")], exitCodes: contactsExit,
             outputSchema: "Page"),
        leaf(name: "get", description: "Fetch one contact by its stable external ID. Ambiguous or missing matches are reported, never silently resolved. Read-only.",
             params: [string("external-id", "External ID", required: true)], exitCodes: [contactsExit, queryExit].flatMap { $0 },
             outputSchema: "ContactPayload"),
        leaf(name: "query", description: "Query contacts by up to three AND-combined filters (name, email, phone, organization, postal code, or kind). Read-only.",
             params: [string("name", "Name filter"), string("email", "Email filter"), string("phone", "Phone filter"),
                      string("organization", "Organization filter"), string("postal-code", "Postal code filter"), string("kind", "person|organization"),
                      int("limit", "Page size"), string("cursor", "Opaque cursor")],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, outputSchema: "Page"),
        leaf(name: "create", description: "Create a contact in the verified iCloud container. Requires --dry-run (preview) or --apply (persist); every created contact must carry a unique external_id.",
             mutates: true, params: [string("input", "JSON file", type: .file), bool("stdin", "Read JSON from stdin"),
                                     bool("apply", "Persist (else dry-run)"), bool("idempotent", "Opt-in create retry")],
             exitCodes: contactsExit, safety: dryRunApply, inputSchema: "ContactPayload", outputSchema: "ContactWriteResult"),
        leaf(name: "edit", description: "Apply a partial edit to a contact identified by external_id; omitted fields are preserved. Requires --dry-run or --apply.",
             mutates: true, params: [string("external-id", "External ID", required: true), string("input", "JSON file", type: .file),
                                     bool("stdin", "Read JSON from stdin")], exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: dryRunApply,
             inputSchema: "ContactPatch"),
        leaf(name: "avatar verify", description: "Check whether a contact's avatar can be read back, returning a tri-state result (readback_confirmed, not_available, or verification_unknown). Read-only.",
             params: [string("external-id", "External ID", required: true)], exitCodes: [contactsExit, queryExit].flatMap { $0 },
             outputSchema: "AvatarWriteVerification"),
        leaf(name: "avatar edit", description: "Write an avatar image to an existing contact. Requires --dry-run or --apply.",
             mutates: true, params: [string("external-id", "External ID", required: true), string("image", "Image file", type: .file)],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: dryRunApply,
             outputSchema: "AvatarWriteVerification"),
        leaf(name: "avatar replace", description: "Replace a contact's avatar image. Requires --apply and the exact confirmation phrase \"RECREATE CONTACT\".",
             mutates: true, params: [string("external-id", "External ID", required: true), string("image", "Image file", type: .file)],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: avatarReplace),
        leaf(name: "delete", description: "Delete a contact by external_id. Requires --apply and the exact confirmation phrase \"DELETE CONTACT\".",
             mutates: true, params: [string("external-id", "External ID", required: true), bool("ignore-not-found", "Opt-in delete retry")],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: deleteContact),
        leaf(name: "external-id migrate", description: "Change a contact's external ID from one value to another. Requires --apply and the exact confirmation phrase \"CHANGE EXTERNAL ID\".",
             mutates: true, params: [string("from", "Old external ID", required: true), string("to", "New external ID", required: true)],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: migrateContact),
        leaf(name: "export", description: "Export a full JSON snapshot of the contacts in the selected container. Read-only; optionally write to a file with the output param.",
             params: [string("output", "Output file", type: .file)], exitCodes: contactsExit),
    ])

    static let mail = group(name: "mail", description: "Read-only Mail access over the local SQLite store with a bounded Apple Events fallback.", subcommands: [
        leaf(name: "doctor", description: "Probe the Mail store and capability status (SQLite fast-path availability, fallback, and permission state). Read-only; run before relying on direct-store reads.", exitCodes: mailExit),
        leaf(name: "accounts", description: "List mail accounts discovered in the local store. Read-only; account IDs are opaque adapter values.", exitCodes: mailExit, outputSchema: "ListResult"),
        leaf(name: "mailboxes", description: "List mailboxes, optionally scoped to one account by opaque ID. Read-only.",
             params: [string("account-id", "Account ID")], exitCodes: mailExit, outputSchema: "ListResult"),
        leaf(name: "threads", description: "List message threads with bounded pagination. Read-only; default limit 50, max 200.", params: [int("limit", "Page size")], exitCodes: mailExit, outputSchema: "Page"),
        leaf(name: "query", description: "Query message metadata with bounded cursor pagination. Read-only; never reads message bodies.",
             params: [string("account-id", "Account ID"), string("mailbox-id", "Mailbox ID"), string("from", "Sender filter"), string("to", "Recipient filter"), string("subject", "Subject filter"), string("received-after", "ISO 8601 lower bound"), string("received-before", "ISO 8601 upper bound"), bool("unread", "Unread only"), bool("flagged", "Flagged only"), bool("has-attachment", "Has attachment only"), int("limit", "Page size", default: "50"), string("cursor", "Opaque cursor")], exitCodes: mailExit,
             outputSchema: "MailQueryResult"),
        leaf(name: "search", description: "Full-text search cached message text under a one-second budget, scanning at most 200 candidates. Read-only.",
             params: [string("text", "Search text", required: true), string("account-id", "Account ID"), string("mailbox-id", "Mailbox ID"), string("from", "Sender filter"), string("to", "Recipient filter"), string("subject", "Subject filter"), string("received-after", "ISO 8601 lower bound"), string("received-before", "ISO 8601 upper bound"), bool("unread", "Unread only"), bool("flagged", "Flagged only"), bool("has-attachment", "Has attachment only"), int("limit", "Page size")], exitCodes: mailExit),
        leaf(name: "get", description: "Fetch one message by opaque ID. Defaults to metadata; content=text reads a bounded plain-text projection and content=raw writes RFC 822 to the output file, never into JSON.",
             params: [string("id", "Message ID", required: true), string("content", "metadata|text|raw"), string("output", "Output file", type: .file)], exitCodes: mailExit,
             outputSchema: "MailMessageMetadata"),
        leaf(name: "reveal", description: "Reveal one message visibly in Mail.app. An explicit visible operation that may launch and activate Mail.app.",
             params: [string("id", "Message ID", required: true)], exitCodes: mailExit),
        leaf(name: "attachments verify", description: "Compare SQLite row counts with cached MIME part counts for one message. Read-only; never returns attachment names or paths.",
             params: [string("id", "Message ID", required: true)], exitCodes: mailExit),
        leaf(name: "attachments export", description: "Export cached attachments for one message to a directory. Refuses overwrite and never writes bytes to JSON or stdout.",
             params: [string("id", "Message ID", required: true), string("output", "Output directory", type: .file)], exitCodes: mailExit),
    ])

    static let calendar = group(name: "calendar", description: "Query and manage calendar events in the uniquely verified iCloud CalDAV source.", subcommands: [
        leaf(name: "permission", description: "Report Calendar full-access authorization status. Read-only; write-only access is not readable.", exitCodes: calendarExit),
        leaf(name: "sources", description: "List EventKit sources and mark the selected iCloud CalDAV source. Read-only.", exitCodes: calendarExit, outputSchema: "ListResult"),
        leaf(name: "calendars", description: "List calendars in the selected iCloud source. Read-only.", exitCodes: calendarExit, outputSchema: "ListResult"),
        leaf(name: "query", description: "Query events in a bounded range (start before end, at most 366 days). Read-only; default limit 50, max 200.",
             params: [string("start", "Start ISO 8601", required: true), string("end", "End ISO 8601", required: true), string("calendar", "Calendar selector"), string("title", "Title filter"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: calendarExit,
             outputSchema: "Page"),
        leaf(name: "conflicts", description: "Scan event-time overlaps in a range, treating adjacent boundaries as non-conflicting (max 200 events). Read-only.",
             params: [string("start", "Start ISO 8601", required: true), string("end", "End ISO 8601", required: true), string("calendar", "Calendar selector")], exitCodes: calendarExit),
        leaf(name: "get", description: "Fetch one event by opaque ID. Read-only.",
             params: [string("id", "Event ID", required: true)], exitCodes: calendarExit,
             outputSchema: "CalendarEventPayload"),
        leaf(name: "create", description: "Create an event in an iCloud calendar. Requires --dry-run or --apply; returns the created payload.",
             mutates: true, params: [string("input", "JSON file", type: .file), bool("idempotent", "Opt-in create retry")], exitCodes: calendarExit, safety: dryRunApply,
             inputSchema: "CalendarEventInput", outputSchema: "CalendarEventPayload"),
        leaf(name: "edit", description: "Partially edit an event by opaque ID. Requires --dry-run or --apply; recurring edits require span=this|future in params.",
             mutates: true, params: [string("id", "Event ID", required: true), string("input", "JSON file", type: .file), string("span", "this|future")], exitCodes: calendarExit, safety: dryRunApply,
             inputSchema: "CalendarEventPatch"),
        leaf(name: "delete", description: "Delete an event by opaque ID. Requires --apply and --confirm \"DELETE EVENT\"; recurring deletes require span=this|future in params.",
             mutates: true, params: [string("id", "Event ID", required: true), string("span", "this|future")], exitCodes: calendarExit, safety: deleteEvent),
    ])

    static let reminders = group(name: "reminders", description: "Query and manage reminders in the uniquely verified iCloud CalDAV source.", subcommands: [
        leaf(name: "permission", description: "Report Reminders full-access authorization status. Read-only.", exitCodes: remindersExit),
        leaf(name: "sources", description: "List reminder-capable EventKit sources. Read-only.", exitCodes: remindersExit),
        leaf(name: "lists", description: "List reminder lists in the selected iCloud source. Read-only.", exitCodes: remindersExit, outputSchema: "ListResult"),
        leaf(name: "query", description: "Query reminders with bounded cursor pagination and optional filters (list, title, status). Read-only.",
             params: [string("list", "List selector"), string("title", "Title filter"), string("status", "Status filter"), string("due-start", "Due start ISO 8601"), string("due-end", "Due end ISO 8601"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: remindersExit,
             outputSchema: "Page"),
        leaf(name: "get", description: "Fetch one reminder by opaque ID. Read-only.",
             params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit,
             outputSchema: "ReminderPayload"),
        leaf(name: "create", description: "Create a reminder in a writable iCloud list. Requires --dry-run or --apply; returns read-back verification.",
             mutates: true, params: [string("input", "JSON file", type: .file), bool("idempotent", "Opt-in create retry")], exitCodes: remindersExit, safety: dryRunApply,
             inputSchema: "ReminderInput", outputSchema: "ReminderPayload"),
        leaf(name: "edit", description: "Partially edit a reminder by opaque ID (omitted fields are preserved). Requires --dry-run or --apply.",
             mutates: true, params: [string("id", "Reminder ID", required: true), string("input", "JSON file", type: .file)], exitCodes: remindersExit, safety: dryRunApply,
             inputSchema: "ReminderPatch"),
        leaf(name: "complete", description: "Mark a reminder complete with an explicit completion date. Requires --dry-run or --apply; repeated apply is a safe no-op.",
             mutates: true, params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit, safety: dryRunApply),
        leaf(name: "reopen", description: "Clear a reminder's completion state. Requires --dry-run or --apply; repeated apply is a safe no-op.",
             mutates: true, params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit, safety: dryRunApply),
        leaf(name: "delete", description: "Delete a reminder from its writable iCloud list. Requires --apply and --confirm \"DELETE REMINDER\".",
             mutates: true, params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit, safety: deleteReminder),
    ])

    static let photos = group(name: "photos", description: "Query photo metadata and export via public PhotoKit.", subcommands: [
        leaf(name: "permission", description: "Report Photos authorization status without prompting. Read-only; set request=true in params to explicitly prompt.", params: [bool("request", "Explicitly request Photos authorization")], exitCodes: photosExit),
        leaf(name: "albums", description: "List photo albums with bounded pagination. Read-only; album names are not selectors because duplicate titles are valid.",
             params: [string("kind", "user|smart|all"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: photosExit,
             outputSchema: "Page"),
        leaf(name: "query", description: "Query asset metadata without requesting image/video bytes or triggering iCloud downloads. Read-only.", params: [string("start", "Start ISO 8601", required: true), string("end", "End ISO 8601", required: true), string("album-id", "Opaque album ID"), string("media", "Media kind"), string("favorite", "true|false"), bool("include-hidden", "Include hidden assets"), bool("include-location", "Include exact location"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: photosExit, outputSchema: "Page"),
        leaf(name: "get", description: "Fetch one asset's metadata by opaque ID. Read-only; never returns media bytes.",
             params: [string("id", "Asset ID", required: true), bool("include-location", "Include exact location")], exitCodes: photosExit,
             outputSchema: "PhotoAssetPayload"),
        leaf(name: "export", description: "Export one asset to a file. Defaults to no network and refuses overwrite; writes bytes only to the output file, never to JSON.",
             params: [string("id", "Asset ID", required: true), string("output", "Output file", type: .file), string("variant", "Export variant"), bool("allow-network", "Allow iCloud download")], exitCodes: photosExit,
             outputSchema: "PhotoExportPayload"),
    ])

    static let notes = group(name: "notes", description: "Bounded Notes.app Automation access through the public scripting dictionary.", subcommands: [
        leaf(name: "permission", description: "Report Notes Automation consent status. Read-only; set request=true in params to explicitly prompt.", params: [bool("request", "Explicitly request Automation consent")], exitCodes: notesExit),
        leaf(name: "accounts", description: "List note accounts. Read-only.", exitCodes: notesExit, outputSchema: "ListResult"),
        leaf(name: "folders", description: "List note folders, optionally scoped to one account by opaque ID. Read-only.",
             params: [string("account-id", "Account ID"), string("parent-id", "Parent folder ID"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: notesExit,
             outputSchema: "ListResult"),
        leaf(name: "query", description: "Query note metadata with bounded pagination. Read-only; never fetches body for every note.", params: [string("account-id", "Account ID"), string("folder-id", "Folder ID"), string("title", "Title filter"), string("modified-after", "ISO 8601 timestamp"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: notesExit, outputSchema: "Page"),
        leaf(name: "get", description: "Fetch one note by opaque ID, with optional --body plain|html projection. Read-only; body never enters logs.",
             params: [string("id", "Note ID", required: true), string("body", "Body format"), bool("include-attachments", "Include attachment metadata")], exitCodes: notesExit,
             outputSchema: "NotesNotePayload"),
        leaf(name: "create", description: "Create a note in the bound iCloud write account. Requires --dry-run or --apply; titles/bodies must come from stdin or a file.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesCreateInput"),
        leaf(name: "rename", description: "Rename a note by opaque ID. Requires --dry-run or --apply; the exact current name is required.",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesRenameInput"),
        leaf(name: "move", description: "Move a note by opaque ID. Requires --dry-run or --apply; cross-account moves are rejected.",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesMoveInput"),
        leaf(name: "delete", description: "Soft-delete a note by opaque ID. Requires structured stale-detection input, --apply, and --confirm \"DELETE NOTE\"; permanent deletion is UI-only.",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: deleteNote,
             inputSchema: "NotesDeleteInput"),
        leaf(name: "edit-body", description: "Replace a simple, attachment-free note body. Requires --dry-run or --apply and the exact current plain-text SHA-256.",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesEditBodyInput"),
        leaf(name: "folder create", description: "Create a folder in the bound iCloud write account. Requires --dry-run or --apply.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesFolderCreateInput"),
        leaf(name: "folder rename", description: "Rename a folder by opaque ID. Requires --dry-run or --apply; the exact current name is required.",
             mutates: true, params: [string("id", "Folder ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesFolderRenameInput"),
        leaf(name: "folder move", description: "Move a folder within the bound account. Requires --dry-run or --apply; cycles and cross-account moves are rejected.",
             mutates: true, params: [string("id", "Folder ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesFolderMoveInput"),
        leaf(name: "folder delete", description: "Delete one verified empty folder. Requires --dry-run or --apply; non-empty or default folders are rejected.",
             mutates: true, params: [string("id", "Folder ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: deleteNotesFolder,
             inputSchema: "NotesFolderDeleteInput"),
        leaf(name: "write-account status", description: "Show the bound Notes write account. Read-only.", exitCodes: notesExit),
        leaf(name: "write-account bind", description: "Bind the Notes iCloud write account by opaque account ID. Requires --dry-run or --apply.",
             mutates: true, params: [string("account-id", "Account ID", required: true)], exitCodes: notesExit, safety: bindNotesAccount),
        leaf(name: "write-account clear", description: "Clear the bound Notes write account. Requires --dry-run or --apply.",
             mutates: true, exitCodes: notesExit, safety: clearNotesAccount),
    ])

    static let shortcuts = group(name: "shortcuts", description: "Run and author shortcuts; bounded read-only classification and guarded copy-first editing.", subcommands: [
        leaf(name: "permission", description: "Report Shortcuts Events Automation status. Read-only; set request=true in params to explicitly prompt.", params: [bool("request", "Explicitly request Automation consent")], exitCodes: shortcutsExit),
        leaf(name: "list", description: "List shortcuts with bounded pagination. Read-only.",
             params: [int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: shortcutsExit,
             outputSchema: "Page"),
        leaf(name: "get", description: "Fetch one shortcut's public metadata by opaque ID. Read-only.",
             params: [string("id", "Shortcut ID", required: true)], exitCodes: shortcutsExit,
             outputSchema: "Page"),
        leaf(name: "folders", description: "List shortcut folders. Read-only.", params: [int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: shortcutsExit, outputSchema: "ListResult"),
        leaf(name: "run", description: "Run one shortcut by opaque ID. Requires --apply and --confirm \"RUN SHORTCUT\"; timeout outcomes are never retried.",
             mutates: true, params: [string("id", "Shortcut ID", required: true), strings("input-path", "Input files"), string("output-path", "Output file", type: .file), string("output-type", "Output UTI"), int("timeout", "Timeout seconds")], exitCodes: shortcutsExit, safety: runShortcut),
        leaf(name: "move", description: "Move a shortcut between folders. Requires --dry-run or --apply and immediate identity verification.",
             mutates: true, params: [string("id", "Shortcut ID", required: true), string("destination-folder-id", "Destination folder ID", required: true)], exitCodes: shortcutsExit, safety: moveShortcut),
        leaf(name: "create", description: "Create a shortcut from .cherri source. Requires --dry-run or --apply; dry-run is the default and never imports.",
             mutates: true, params: [string("source", ".cherri file", type: .file, required: true), string("signing-mode", "Signing mode"), bool("idempotent", "Opt-in create retry")], exitCodes: shortcutsExit, safety: createManagedShortcut),
        leaf(name: "update", description: "Update a managed shortcut from .cherri source. Requires --dry-run or --apply and the expected source hash.",
             mutates: true, params: [string("id", "Shortcut ID", required: true), string("source", ".cherri file", type: .file, required: true), string("expected-source-sha256", "Expected source SHA-256", required: true), string("strategy", "replace|retain-old", required: true), string("signing-mode", "Signing mode")], exitCodes: shortcutsExit, safety: updateManagedShortcut),
        leaf(name: "author validate", description: "Validate bounded .cherri source and compile an unsigned artifact privately. Read-only; never echoes source content.",
             params: [string("source", ".cherri file", type: .file, required: true)], exitCodes: shortcutsExit),
        leaf(name: "author build", description: "Build and sign a shortcut without importing. Refuses overwrite; never echoes source content.",
             params: [string("source", ".cherri file", type: .file, required: true), string("output", "Output file", type: .file, required: true), string("signing-mode", "Signing mode")], exitCodes: shortcutsExit),
        leaf(name: "managed list", description: "List private managed shortcut identities and hashes. Read-only.", exitCodes: shortcutsExit),
        leaf(name: "managed forget", description: "Remove registry/receipt state for a managed shortcut. Requires --dry-run or --apply; never deletes the Shortcut itself.",
             mutates: true, params: [string("id", "Shortcut ID", required: true)], exitCodes: shortcutsExit, safety: forgetManagedShortcut),
        leaf(name: "edit inspect", description: "Classify one bounded local .cherri/.shortcut artifact. Read-only; never imports, opens, stores, or echoes it.",
             params: [string("input", "Artifact file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "edit plan", description: "Validate a bounded action-level edit plan against the exact input SHA-256. Read-only.",
             params: [string("input", "Artifact file", type: .file), string("patch", "Patch file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "edit copy", description: "Apply an edit to a verified duplicate. Requires --apply and --confirm \"EDIT SHORTCUT COPY\"; never modifies the original.",
             mutates: true, params: [string("input", "Artifact file", type: .file, required: true), string("patch", "Patch file", type: .file, required: true), string("expected-editor-name-sha256", "Expected editor-name SHA-256", required: true)], exitCodes: shortcutsExit, safety: editCopy),
        leaf(name: "edit ui-inspect", description: "Inspect bounded Shortcuts AX structure. Read-only; never prompts, activates, clicks, or types.", exitCodes: shortcutsExit),
    ])

    static let safari = group(name: "safari", description: "Bounded Safari bookmarks and Reading List over a read-only plist snapshot plus guarded local-only mutation.", subcommands: [
        leaf(name: "permission", description: "Report Bookmarks.plist readability and Safari Automation status. Read-only; set request=true in params to explicitly prompt.", params: [bool("request", "Explicitly request Automation consent")], exitCodes: safariExit),
        leaf(name: "bookmarks list", description: "List bookmarks and folders, excluding Reading List. Read-only; bounded pagination.",
             params: [string("folder-id", "Folder ID"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "bookmarks query", description: "Query bookmark metadata with AND filters (text, url). Read-only.",
             params: [string("text", "Text filter"), string("url", "URL filter")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "bookmarks get", description: "Fetch one bookmark or folder by opaque ID. Read-only.",
             params: [string("id", "Bookmark ID", required: true)], exitCodes: safariExit,
             outputSchema: "SafariBookmarkPayload"),
        leaf(name: "bookmarks create", description: "Create a local bookmark. Requires --dry-run or --apply; apply requires Safari fully quit and atomic replacement.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "bookmarks edit", description: "Edit a local bookmark. Requires --dry-run or --apply; local-only and does not sync to iCloud.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "bookmarks move", description: "Move a bookmark within the local Safari tree. Requires --dry-run or --apply.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "bookmarks delete", description: "Delete a local bookmark. Requires --dry-run or --apply; local-only.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: deleteSafariBookmark, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "folders create", description: "Create a local Safari bookmark folder. Requires --dry-run or --apply.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "folders rename", description: "Rename a local Safari bookmark folder. Requires --dry-run or --apply.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "folders move", description: "Move a local Safari bookmark folder. Requires --dry-run or --apply.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "folders delete", description: "Delete one verified empty local Safari bookmark folder. Requires --dry-run or --apply.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: deleteSafariFolder, inputSchema: "SafariLocalMutationInput"),
        leaf(name: "reading-list list", description: "List Reading List metadata with bounded pagination. Read-only.",
             params: [int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "reading-list query", description: "Query Reading List metadata with AND filters (text, url, read). Read-only.",
             params: [string("text", "Text filter"), string("url", "URL filter"), string("read", "Read-state filter"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "reading-list get", description: "Fetch one Reading List item by opaque ID. Read-only.",
             params: [string("id", "Item ID", required: true)], exitCodes: safariExit,
             outputSchema: "SafariReadingListItemPayload"),
        leaf(name: "reading-list add", description: "Add a Reading List item through Safari's official AppleScript. Requires --dry-run or --apply; five-second deadline with immediate read-back.",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply,
             inputSchema: "SafariReadingListAddInput"),
    ])

    static let messages = group(name: "messages", description: "Read-only recent Messages (iMessage/SMS).", subcommands: [
        leaf(name: "permission", description: "Check Messages read permission and Full Disk Access status.", exitCodes: messagesExit,
             outputSchema: "MessagesPermissionStatus"),
        leaf(name: "recent", description: "List recent messages (metadata + bounded text projection).",
             params: [int("limit", "Page size", default: "50"), string("cursor", "Opaque cursor"), string("service", "imessage|sms")], exitCodes: messagesExit,
             outputSchema: "MessagesRecentResult"),
    ])

    static let phoneCalls = group(name: "phone-calls", description: "Read-only recent call history (Phone/FaceTime).", subcommands: [
        leaf(name: "permission", description: "Check Call History read permission and Full Disk Access status.", exitCodes: phoneCallsExit,
             outputSchema: "PhoneCallsPermissionStatus"),
        leaf(name: "recent", description: "List recent calls (direction/time/duration/missed state; never counterparty identifiers).",
             params: [int("limit", "Page size", default: "50"), string("cursor", "Opaque cursor")], exitCodes: phoneCallsExit,
             outputSchema: "PhoneCallsRecentResult"),
    ])
}
