import Foundation

/// Per-adapter command definitions for the machine-readable registry.
extension CommandRegistry {

    static let resources = leaf(
        name: "resources",
        description: "List every data resource with selection, permission, and limitations.",
        usage: "mpia resources --format json",
        outputSchema: "DataResourcesResult"
    )

    static let contacts = group(name: "contacts", description: "Query and manage contacts.", subcommands: [
        leaf(name: "permission", description: "Check Contacts authorization.", usage: "mpia contacts permission", exitCodes: contactsExit),
        leaf(name: "count", description: "Count contacts.", usage: "mpia contacts count [--format json]", exitCodes: contactsExit),
        leaf(name: "containers", description: "List contact containers.", usage: "mpia contacts containers", exitCodes: contactsExit),
        leaf(name: "container", description: "Show the selected container.", usage: "mpia contacts container", exitCodes: contactsExit,
        outputSchema: "ContactContainer"),
        leaf(name: "list", description: "List contacts with pagination.", usage: "mpia contacts list --format json",
             params: [int("limit", "Page size", default: "50"), string("cursor", "Opaque cursor")], exitCodes: contactsExit,
             outputSchema: "Page"),
        leaf(name: "get", description: "Get one contact by external ID.", usage: "mpia contacts get --external-id <id> --format json",
             params: [string("external-id", "External ID", required: true)], exitCodes: [contactsExit, queryExit].flatMap { $0 },
             outputSchema: "ContactPayload"),
        leaf(name: "query", description: "Query contacts with AND semantics.", usage: "mpia contacts query [filters] --format json",
             params: [string("name", "Name filter"), string("email", "Email filter"), string("phone", "Phone filter"),
                      string("organization", "Organization filter"), string("postal-code", "Postal code filter"), string("kind", "person|organization")],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, outputSchema: "Page"),
        leaf(name: "create", description: "Create a contact.", usage: "mpia contacts create --input <file>|--stdin --dry-run|--apply [--idempotent]",
             mutates: true, params: [string("input", "JSON file", type: .file), bool("stdin", "Read JSON from stdin"),
                                     bool("apply", "Persist (else dry-run)"), bool("idempotent", "Opt-in create retry")],
             exitCodes: contactsExit, safety: dryRunApply, inputSchema: "ContactPayload", outputSchema: "ContactWriteResult"),
        leaf(name: "edit", description: "Partially edit a contact.", usage: "mpia contacts edit --external-id <id> --input <file>|--stdin --dry-run|--apply",
             mutates: true, params: [string("external-id", "External ID", required: true), string("input", "JSON file", type: .file),
                                     bool("stdin", "Read JSON from stdin")], exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: dryRunApply,
             inputSchema: "ContactPatch"),
        leaf(name: "avatar verify", description: "Check a contact avatar read-back.", usage: "mpia contacts avatar verify --external-id <id> --format json",
             params: [string("external-id", "External ID", required: true)], exitCodes: [contactsExit, queryExit].flatMap { $0 },
             outputSchema: "AvatarWriteVerification"),
        leaf(name: "avatar replace", description: "Replace a contact avatar.", usage: "mpia contacts avatar replace --external-id <id> --image <file> --apply --confirm \"RECREATE CONTACT\"",
             mutates: true, params: [string("external-id", "External ID", required: true), string("image", "Image file", type: .file)],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: avatarReplace),
        leaf(name: "delete", description: "Delete a contact.", usage: "mpia contacts delete --external-id <id> --apply --confirm \"DELETE CONTACT\"",
             mutates: true, params: [string("external-id", "External ID", required: true), bool("ignore-not-found", "Opt-in delete retry")],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: deleteContact),
        leaf(name: "external-id migrate", description: "Migrate a contact external ID.", usage: "mpia contacts external-id migrate --from <old> --to <new> --apply --confirm \"CHANGE EXTERNAL ID\"",
             mutates: true, params: [string("from", "Old external ID", required: true), string("to", "New external ID", required: true)],
             exitCodes: [contactsExit, queryExit].flatMap { $0 }, safety: migrateContact),
        leaf(name: "export", description: "Export a full JSON snapshot.", usage: "mpia contacts export --format json [--output <file>]",
             params: [string("output", "Output file", type: .file)], exitCodes: contactsExit),
    ])

    static let mail = group(name: "mail", description: "Read-only Mail access.", subcommands: [
        leaf(name: "doctor", description: "Probe Mail-store and capability status.", usage: "mpia mail doctor --format json", exitCodes: mailExit),
        leaf(name: "accounts", description: "List mail accounts.", usage: "mpia mail accounts --format json", exitCodes: mailExit, outputSchema: "ListResult"),
        leaf(name: "mailboxes", description: "List mailboxes.", usage: "mpia mail mailboxes [--account-id <id>] --format json",
             params: [string("account-id", "Account ID")], exitCodes: mailExit, outputSchema: "ListResult"),
        leaf(name: "threads", description: "List message threads.", usage: "mpia mail threads --format json", params: [int("limit", "Page size")], exitCodes: mailExit, outputSchema: "Page"),
        leaf(name: "query", description: "Query message metadata.", usage: "mpia mail query [filters] [--limit <n>] [--cursor <c>] --format json",
             params: [int("limit", "Page size", default: "50"), string("cursor", "Opaque cursor")], exitCodes: mailExit,
             outputSchema: "MailQueryResult"),
        leaf(name: "search", description: "Full-text search messages.", usage: "mpia mail search <text> --format json",
             params: [string("text", "Search text", required: true)], exitCodes: mailExit),
        leaf(name: "get", description: "Get one message (metadata/text/raw).", usage: "mpia mail get --id <id> [--content metadata|text|raw] --format json",
             params: [string("id", "Message ID", required: true), string("content", "metadata|text|raw")], exitCodes: mailExit,
             outputSchema: "MailMessageMetadata"),
        leaf(name: "reveal", description: "Reveal a message in Mail.app.", usage: "mpia mail reveal --id <id> --format json",
             params: [string("id", "Message ID", required: true)], exitCodes: mailExit),
        leaf(name: "attachments verify", description: "Compare attachment counts.", usage: "mpia mail attachments verify --id <id> --format json",
             params: [string("id", "Message ID", required: true)], exitCodes: mailExit),
        leaf(name: "attachments export", description: "Export attachments to a directory.", usage: "mpia mail attachments export --id <id> --output <dir>",
             params: [string("id", "Message ID", required: true), string("output", "Output directory", type: .file)], exitCodes: mailExit),
    ])

    static let calendar = group(name: "calendar", description: "Query and manage calendar events.", subcommands: [
        leaf(name: "permission", description: "Check Calendar full-access authorization.", usage: "mpia calendar permission", exitCodes: calendarExit),
        leaf(name: "sources", description: "List calendar sources.", usage: "mpia calendar sources --format json", exitCodes: calendarExit, outputSchema: "ListResult"),
        leaf(name: "calendars", description: "List calendars.", usage: "mpia calendar calendars --format json", exitCodes: calendarExit, outputSchema: "ListResult"),
        leaf(name: "query", description: "Query events in a range.", usage: "mpia calendar query --start <iso> --end <iso> --format json",
             params: [string("start", "Start ISO 8601", required: true), string("end", "End ISO 8601", required: true)], exitCodes: calendarExit,
             outputSchema: "Page"),
        leaf(name: "conflicts", description: "Scan event conflicts.", usage: "mpia calendar conflicts --start <iso> --end <iso> --format json",
             params: [string("start", "Start ISO 8601", required: true), string("end", "End ISO 8601", required: true)], exitCodes: calendarExit),
        leaf(name: "get", description: "Get one event.", usage: "mpia calendar get --id <id> --format json",
             params: [string("id", "Event ID", required: true)], exitCodes: calendarExit,
             outputSchema: "CalendarEventPayload"),
        leaf(name: "create", description: "Create an event.", usage: "mpia calendar create --input event.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: calendarExit, safety: dryRunApply,
             inputSchema: "CalendarEventInput", outputSchema: "CalendarEventPayload"),
        leaf(name: "edit", description: "Edit an event.", usage: "mpia calendar edit --id <id> --input patch.json --dry-run|--apply",
             mutates: true, params: [string("id", "Event ID", required: true), string("input", "JSON file", type: .file)], exitCodes: calendarExit, safety: dryRunApply,
             inputSchema: "CalendarEventPatch"),
        leaf(name: "delete", description: "Delete an event.", usage: "mpia calendar delete --id <id> --apply --confirm \"DELETE EVENT\"",
             mutates: true, params: [string("id", "Event ID", required: true)], exitCodes: calendarExit, safety: deleteEvent),
    ])

    static let reminders = group(name: "reminders", description: "Query and manage reminders.", subcommands: [
        leaf(name: "permission", description: "Check Reminders full-access authorization.", usage: "mpia reminders permission", exitCodes: remindersExit),
        leaf(name: "sources", description: "List reminder sources.", usage: "mpia reminders sources --format json", exitCodes: remindersExit),
        leaf(name: "lists", description: "List reminder lists.", usage: "mpia reminders lists --format json", exitCodes: remindersExit, outputSchema: "ListResult"),
        leaf(name: "query", description: "Query reminders.", usage: "mpia reminders query [filters] --format json",
             params: [string("list", "List selector"), string("title", "Title filter"), string("status", "Status filter")], exitCodes: remindersExit,
             outputSchema: "Page"),
        leaf(name: "get", description: "Get one reminder.", usage: "mpia reminders get --id <id> --format json",
             params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit,
             outputSchema: "ReminderPayload"),
        leaf(name: "create", description: "Create a reminder.", usage: "mpia reminders create --input reminder.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: remindersExit, safety: dryRunApply,
             inputSchema: "ReminderInput", outputSchema: "ReminderPayload"),
        leaf(name: "edit", description: "Edit a reminder.", usage: "mpia reminders edit --id <id> --input patch.json --dry-run|--apply",
             mutates: true, params: [string("id", "Reminder ID", required: true), string("input", "JSON file", type: .file)], exitCodes: remindersExit, safety: dryRunApply,
             inputSchema: "ReminderPatch"),
        leaf(name: "complete", description: "Complete a reminder.", usage: "mpia reminders complete --id <id> --dry-run|--apply",
             mutates: true, params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit, safety: dryRunApply),
        leaf(name: "reopen", description: "Reopen a reminder.", usage: "mpia reminders reopen --id <id> --dry-run|--apply",
             mutates: true, params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit, safety: dryRunApply),
        leaf(name: "delete", description: "Delete a reminder.", usage: "mpia reminders delete --id <id> --apply --confirm \"DELETE REMINDER\"",
             mutates: true, params: [string("id", "Reminder ID", required: true)], exitCodes: remindersExit, safety: deleteReminder),
    ])

    static let photos = group(name: "photos", description: "Query photo metadata and export.", subcommands: [
        leaf(name: "permission", description: "Check Photos authorization (status only).", usage: "mpia photos permission", exitCodes: photosExit),
        leaf(name: "albums", description: "List photo albums.", usage: "mpia photos albums --format json",
             params: [int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: photosExit,
             outputSchema: "Page"),
        leaf(name: "query", description: "Query asset metadata.", usage: "mpia photos query [filters] --format json", exitCodes: photosExit, outputSchema: "Page"),
        leaf(name: "get", description: "Get one asset metadata.", usage: "mpia photos get --id <id> --format json",
             params: [string("id", "Asset ID", required: true)], exitCodes: photosExit,
             outputSchema: "PhotoAssetPayload"),
        leaf(name: "export", description: "Export one asset.", usage: "mpia photos export --id <id> --output <file>",
             params: [string("id", "Asset ID", required: true), string("output", "Output file", type: .file)], exitCodes: photosExit,
             outputSchema: "PhotoExportPayload"),
    ])

    static let notes = group(name: "notes", description: "Bounded Notes.app Automation access.", subcommands: [
        leaf(name: "permission", description: "Check Notes Automation consent (status only).", usage: "mpia notes permission", exitCodes: notesExit),
        leaf(name: "accounts", description: "List note accounts.", usage: "mpia notes accounts", exitCodes: notesExit, outputSchema: "ListResult"),
        leaf(name: "folders", description: "List note folders.", usage: "mpia notes folders [--account-id <id>] --format json",
             params: [string("account-id", "Account ID")], exitCodes: notesExit,
             outputSchema: "ListResult"),
        leaf(name: "query", description: "Query note metadata.", usage: "mpia notes query [filters] --format json", exitCodes: notesExit, outputSchema: "Page"),
        leaf(name: "get", description: "Get one note.", usage: "mpia notes get --id <id> [--body plain|html] --format json",
             params: [string("id", "Note ID", required: true), string("body", "Body format")], exitCodes: notesExit,
             outputSchema: "NotesNotePayload"),
        leaf(name: "create", description: "Create a note.", usage: "mpia notes create --input note.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesCreateInput"),
        leaf(name: "rename", description: "Rename a note.", usage: "mpia notes rename --id <id> --input note.json --dry-run|--apply",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesRenameInput"),
        leaf(name: "move", description: "Move a note.", usage: "mpia notes move --id <id> --input note.json --dry-run|--apply",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply),
        leaf(name: "delete", description: "Soft-delete a note.", usage: "mpia notes delete --id <id> --apply --confirm \"DELETE NOTE\"",
             mutates: true, params: [string("id", "Note ID", required: true)], exitCodes: notesExit, safety: deleteNote),
        leaf(name: "edit-body", description: "Replace a note body.", usage: "mpia notes edit-body --id <id> --input note.json --dry-run|--apply",
             mutates: true, params: [string("id", "Note ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesEditBodyInput"),
        leaf(name: "folder create", description: "Create a folder.", usage: "mpia notes folder create --input folder.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesFolderCreateInput"),
        leaf(name: "folder rename", description: "Rename a folder.", usage: "mpia notes folder rename --id <id> --input folder.json --dry-run|--apply",
             mutates: true, params: [string("id", "Folder ID", required: true), string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply,
             inputSchema: "NotesFolderRenameInput"),
        leaf(name: "write-account status", description: "Show the bound write account.", usage: "mpia notes write-account status", exitCodes: notesExit),
        leaf(name: "write-account bind", description: "Bind a write account.", usage: "mpia notes write-account bind --input account.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: notesExit, safety: dryRunApply),
        leaf(name: "write-account clear", description: "Clear the bound write account.", usage: "mpia notes write-account clear --dry-run|--apply",
             mutates: true, exitCodes: notesExit, safety: dryRunApply),
    ])

    static let shortcuts = group(name: "shortcuts", description: "Run and author shortcuts.", subcommands: [
        leaf(name: "permission", description: "Check Shortcuts Events consent (status only).", usage: "mpia shortcuts permission", exitCodes: shortcutsExit),
        leaf(name: "list", description: "List shortcuts.", usage: "mpia shortcuts list --format json",
             params: [int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: shortcutsExit,
             outputSchema: "Page"),
        leaf(name: "get", description: "Get one shortcut.", usage: "mpia shortcuts get --id <id> --format json",
             params: [string("id", "Shortcut ID", required: true)], exitCodes: shortcutsExit,
             outputSchema: "Page"),
        leaf(name: "folders", description: "List shortcut folders.", usage: "mpia shortcuts folders --format json", exitCodes: shortcutsExit, outputSchema: "ListResult"),
        leaf(name: "run", description: "Run a shortcut.", usage: "mpia shortcuts run --id <id> [--input <file>] --format json",
             params: [string("id", "Shortcut ID", required: true), string("input", "Input file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "move", description: "Move a shortcut.", usage: "mpia shortcuts move --id <id> --to <folder> --dry-run|--apply",
             mutates: true, params: [string("id", "Shortcut ID", required: true), string("to", "Destination folder ID", required: true)], exitCodes: shortcutsExit, safety: dryRunApply),
        leaf(name: "create", description: "Create a shortcut from .cherri source.", usage: "mpia shortcuts create --input <file> --dry-run|--apply",
             mutates: true, params: [string("input", ".cherri file", type: .file)], exitCodes: shortcutsExit, safety: dryRunApply),
        leaf(name: "update", description: "Update a managed shortcut.", usage: "mpia shortcuts update --id <id> --input <file> --dry-run|--apply",
             mutates: true, params: [string("id", "Shortcut ID", required: true), string("input", ".cherri file", type: .file)], exitCodes: shortcutsExit, safety: dryRunApply),
        leaf(name: "author validate", description: "Validate .cherri source.", usage: "mpia shortcuts author validate --input <file>",
             params: [string("input", ".cherri file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "author build", description: "Build and sign a shortcut.", usage: "mpia shortcuts author build --input <file> --output <file>",
             params: [string("input", ".cherri file", type: .file), string("output", "Output file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "managed list", description: "List managed shortcuts.", usage: "mpia shortcuts managed list", exitCodes: shortcutsExit),
        leaf(name: "managed forget", description: "Forget a managed shortcut.", usage: "mpia shortcuts managed forget --id <id> --dry-run|--apply",
             mutates: true, params: [string("id", "Shortcut ID", required: true)], exitCodes: shortcutsExit, safety: dryRunApply),
        leaf(name: "edit inspect", description: "Classify a local shortcut artifact.", usage: "mpia shortcuts edit inspect --input <file>",
             params: [string("input", "Artifact file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "edit plan", description: "Plan an action-level edit.", usage: "mpia shortcuts edit plan --input <file> --patch <file>",
             params: [string("input", "Artifact file", type: .file), string("patch", "Patch file", type: .file)], exitCodes: shortcutsExit),
        leaf(name: "edit copy", description: "Apply an edit to a verified copy.", usage: "mpia shortcuts edit copy --input <file> --patch <file> --apply --confirm \"EDIT SHORTCUT COPY\"",
             mutates: true, params: [string("input", "Artifact file", type: .file), string("patch", "Patch file", type: .file)], exitCodes: shortcutsExit, safety: editCopy),
        leaf(name: "edit ui-inspect", description: "Read-only AX structure discovery.", usage: "mpia shortcuts edit ui-inspect", exitCodes: shortcutsExit),
    ])

    static let safari = group(name: "safari", description: "Bounded Safari bookmarks and Reading List.", subcommands: [
        leaf(name: "permission", description: "Check Safari readability and Automation status.", usage: "mpia safari permission", exitCodes: safariExit),
        leaf(name: "bookmarks list", description: "List bookmarks and folders.", usage: "mpia safari bookmarks list --format json",
             params: [string("folder-id", "Folder ID"), int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "bookmarks query", description: "Query bookmarks.", usage: "mpia safari bookmarks query [filters] --format json",
             params: [string("text", "Text filter"), string("url", "URL filter")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "bookmarks get", description: "Get one bookmark.", usage: "mpia safari bookmarks get --id <id> --format json",
             params: [string("id", "Bookmark ID", required: true)], exitCodes: safariExit,
             outputSchema: "SafariBookmarkPayload"),
        leaf(name: "bookmarks create", description: "Create a bookmark.", usage: "mpia safari bookmarks create --input bookmark.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply),
        leaf(name: "bookmarks edit", description: "Edit a bookmark.", usage: "mpia safari bookmarks edit --id <id> --input bookmark.json --dry-run|--apply",
             mutates: true, params: [string("id", "Bookmark ID", required: true), string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply),
        leaf(name: "bookmarks delete", description: "Delete a bookmark.", usage: "mpia safari bookmarks delete --id <id> --dry-run|--apply",
             mutates: true, params: [string("id", "Bookmark ID", required: true)], exitCodes: safariExit, safety: dryRunApply),
        leaf(name: "reading-list list", description: "List Reading List items.", usage: "mpia safari reading-list list --format json",
             params: [int("limit", "Page size"), string("cursor", "Opaque cursor")], exitCodes: safariExit,
             outputSchema: "Page"),
        leaf(name: "reading-list get", description: "Get one Reading List item.", usage: "mpia safari reading-list get --id <id> --format json",
             params: [string("id", "Item ID", required: true)], exitCodes: safariExit,
             outputSchema: "SafariReadingListItemPayload"),
        leaf(name: "reading-list add", description: "Add a Reading List item.", usage: "mpia safari reading-list add --input item.json --dry-run|--apply",
             mutates: true, params: [string("input", "JSON file", type: .file)], exitCodes: safariExit, safety: dryRunApply,
             inputSchema: "SafariReadingListAddInput"),
    ])
}
